# Generated by Django 3.1.1 on 2020-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apifirst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=300)),
            ],
        ),
    ]
